# Numpy

In [1]:
## Install numpy library
## First prefernce, if ANACONDA is installed
## conda install numpy
## Second prefence
## pip install numpy
import numpy as np

In [2]:
myl = [1,2,30,40,-50]
print(type(myl))
myl

<class 'list'>


[1, 2, 30, 40, -50]

In [3]:
# From list create array
mya = np.array(myl)
mya

array([  1,   2,  30,  40, -50])

In [4]:
print(type(mya))

<class 'numpy.ndarray'>


In [5]:
mya.dtype

dtype('int32')

# Shape and size

In [6]:
sh = mya.shape
#print(type(sh))
print(sh)
print(sh[0])

(5,)
5


In [7]:
# returns the total number of elements in the array
mya.size

5

In [8]:
# returns the size (in bytes) of each element in the NumPy array
mya.itemsize

4

In [9]:
# returns data type of the elements
mya.dtype

dtype('int32')

In [10]:
# returns the number of dimensions (axes) of the NumPy array
mya.ndim

1

In [11]:
mylf = [1.0,2.0,3.0,4.0]
mylf

[1.0, 2.0, 3.0, 4.0]

In [12]:
myaf = np.array(mylf)

In [13]:
print(myaf.size)
myaf.itemsize

4


8

In [14]:
print(mya.size)
mya.itemsize

5


4

In [15]:
myaf.dtype


dtype('float64')

In [16]:
myaf.shape

(4,)

In [17]:
## Reshaping my 1-D
mylf = [1.0,2.0,3.0,4.0,10.0,-90,80,100,12,14,13,14]
myaf = np.array(mylf)
print(myaf.shape)
myaf

(12,)


array([  1.,   2.,   3.,   4.,  10., -90.,  80., 100.,  12.,  14.,  13.,
        14.])

In [18]:
X_2D = myaf.reshape((6,2))
print(myaf.shape)
print(X_2D.shape)
print(X_2D)

(12,)
(6, 2)
[[  1.   2.]
 [  3.   4.]
 [ 10. -90.]
 [ 80. 100.]
 [ 12.  14.]
 [ 13.  14.]]


In [19]:
X_3D = myaf.reshape((2,2,3))
print(myaf.shape)
print(X_3D.shape)
print(X_3D)

(12,)
(2, 2, 3)
[[[  1.   2.   3.]
  [  4.  10. -90.]]

 [[ 80. 100.  12.]
  [ 14.  13.  14.]]]


# Statistical Analysis

In [20]:
mylist = [9, 10, -20, 56, -4, 500, -20, 7, 8, 9]
mylist

[9, 10, -20, 56, -4, 500, -20, 7, 8, 9]

In [21]:
mya = np.array(mylist)
mya.dtype

dtype('int32')

In [22]:
#  returns the minimum value of the array
mya.min()

-20

In [23]:
#  returns the maximum value of the array
mya.max()

500

In [24]:
# returns the index of the smallest value in the array 
mya.argmin()

2

In [25]:
# returns the index of the largest value in the array 
mya.argmax()

5

In [26]:
#  returns the sum of all elements in the array
mya.sum()

555

In [27]:
#  returns the mean of all elements in the array
mya.mean()

55.5

In [28]:
#  returns the standard deviation of all elements in the array
mya.std()

149.5073576784768

In [29]:
## np.mean(mya)
## OR
###mya.mean()

# Mathematical operations

In [30]:
a = [1,3,5]
b = [1,2,3]

In [31]:
npa = np.array([1,3,5])
npb = np.array([1,2,3])

In [32]:
# Append
a + b

[1, 3, 5, 1, 2, 3]

In [33]:
# Element-wise addition
npa + npb

array([2, 5, 8])

In [34]:
# Unsupported
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
# Element-wise subtraction
npa - npb


In [ ]:
# Unsupported
a * b

In [ ]:
# Element-wise multiplication
npa * npb

In [ ]:
# Unsupported
a / b

In [ ]:
# Element-wise division
npa / npb

In [ ]:
# square root of each element
np.sqrt(npa)

In [ ]:
# exponential of each element
np.exp(npa)

In [ ]:
# sine of each element
np.sin(npa)

In [ ]:
# log of each element
np.log(npa)

# Special array creation

In [ ]:
# creates a NumPy array of shape (10,) filled with ones.
np.ones(10)

In [ ]:
# creates a NumPy array of shape (5,) filled with zeroes.
np.zeros(5)

In [ ]:
# Creating a Identity matrix
np.eye(2,2)


In [ ]:
np.eye(3,7)

In [ ]:
np.eye(3)

In [ ]:
# generates a NumPy array of evenly spaced values within a specified range.
# arange is a function that creates an array with values from the start value up to, but not including, the end value.
# The arguments 5 and 10 specify the start and end values of the range, respectively.
mya = np.arange(5,10)
mya

In [ ]:
# generates a NumPy array of evenly spaced values within a specified range.
mya = np.arange (5,-10,-2)
mya

In [ ]:
mya = np.arange(0,-11,-2)
mya

In [ ]:
mya = np.arange(100,1000,100)
mya

In [ ]:
# generates a NumPy array of evenly spaced values within a specified range.
#linspace is a function that creates an array with a specified number of evenly spaced values between a start and an end value.
#The first argument, 0, is the start of the interval.
#The second argument, 10, is the end of the interval.
#The third argument, 7, specifies the number of values to generate.
np.linspace (0,10,7)

In [ ]:
np.linspace(100,200, 21)

In [ ]:
# generates a random float number from a uniform distribution 0 to 1
np.random.rand()


In [ ]:
# generates an array of 5 random numbers
np.random.rand(5)

In [ ]:
# generates a 2x3 array of random numbers,
np.random.rand(2,3)

In [ ]:
# generates a random float number from a standard normal distribution 
np.random.randn()

In [ ]:
np.random.randn(5)

In [ ]:
np.random.randn(2,3)

In [ ]:
# generates a single random integer from the uniform distribution over the interval [0,5).
# In this example, np.random.randint(5) returns a random integer from the set {0, 1, 2, 3, 4}.
# The specific values will vary each time you run the code due to the randomness.
np.random.randint(5)

In [ ]:
# In this example, np.random.randint(5, 10) returns a random integer from the set {5, 6, 7, 8, 9}.
np.random.randint(5,10)

In [ ]:
np.random.randint(5,10,2)

# Copy and assignment

In [ ]:
# When you assign one NumPy array to another using the = operator, no new array is created. 
# Instead, both variables point to the same array in memory.

arr1 = np.array([1, 2, 3])
arr2 = arr1  # Assignment
arr2[0] = 99

print(arr1)  # Output: [99, 2, 3]
print(arr2)  # Output: [99, 2, 3]

# In this example, modifying arr2 also changes arr1 because they both refer to the same array in memory.

In [ ]:
# When you copy a NumPy array, a new array is created with the same data as the original. 
# The copied array is independent of the original, meaning changes to one do not affect the other.
arr1 = np.array([1, 2, 3])
arr2 = arr1.copy()  # Copy
arr2[0] = 99

print(arr1)  # Output: [1, 2, 3]
print(arr2)  # Output: [99, 2, 3]
# Here, modifying arr2 does not affect arr1 because arr2 is a separate copy of the original array.